### ISSUE TITLE
Unable to create an instance

### ISSUE THREAD

**Issue by bkvinoth** [awl-techniek/AWL-Services-Citrix#1]
I get below error while installing or testing the applciation
Installing assembly 'C:\Program Files\AWL-Services-Citrix-master\Build\AWL.Services.Console\AWL.Services.Console.exe'.
Affected parameters are:
   logtoconsole = 
   assemblypath = C:\Program Files\AWL-Services-Citrix-master\Build\AWL.Services.Console\AWL.Services.Console.exe
   logfile = C:\Program Files\AWL-Services-Citrix-master\Build\AWL.Services.Console\AWL.Services.Console.InstallLog
Unable to create an instance of the AWL.Services.Console.ServiceInstaller installer type.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
The inner exception System.IndexOutOfRangeException was thrown with the following error message: Settings collection does not contain the requested key: displayName.
Rolling back assembly 'C:\Program Files\AWL-Services-Citrix-master\Build\AWL.Services.Console\AWL.Services.Console.exe'.

**Comment by manuelmarucco** [comment]
The problem is that "displayName" is not define in the AWL.Services.Console.exe.config. The file ServiceInstaller.Designer.cs looks for it and throws the exception.

To solve the problem edit "AWL.Services.Console.exe.config" and add this under the `<configuration> ` tag:
      `
    <appSettings>`
              `<add key="displayName" value="AWL Services"/>`
     ` </appSettings>
`

**Comment by bkvinoth** [comment]
thanks for the information, Am sorry that am very new to coding. I just build using visual studio without any modification of the script and config, Even adding the "AWL.Services.Console.exe.config" didn't help. is there place I need to enter the storefront or DDC address ?

**Comment by manuelmarucco** [comment]
You might be needing the serviceName variable as well and also editing the "AWL.Services.Console.exe.config" should be done after the build. To make things more clear and not needing to edit the exe.config everytime you rebuild the solution I will explain two options you have to solve this.

SOLUTION 1) From Visual Studio, edit the file `App.config` at `Solution 'AWL Services'/AWL.Services.Console/App.config`. You have to define there the key `displayName` and `serviceName`. To do so, the last lines of App.config should be:
```
</entityFramework>
  <appSettings>
    <add key="displayName" value="AWL Services"/>
    <add key="serviceName" value="AWL Services"/>
  </appSettings>
</configuration>
```
Then rebuild the solution and follow the installation procedure:
i) Go to Build folder and copy the files to a logical folder ( Like Program Files )
ii) CMD to this folder and run:
```C:\Windows\Microsoft.NET\Framework64\v4.0.30319\InstallUtil.exe AWL.Services.Console.exe```

SOLUTION 2) From Visual Studio, edit  `ServiceInstaller.Designer.cs`. You will see two private functions called ServiceName and DisplayName. Comment the `return GetConfigValue` line and uncomment the line `return (System.Configuration.....` on both functions. `GetConfigValue` was throwing the exception because it wasn't finding the key "serviceName" and "displayName" on App.config. The other line is just giving a default name if the key is null.

```
		private string ServiceName
		{
			get
			{
				

				//return GetConfigValue("serviceName"); 
                               return (System.Configuration.ConfigurationManager.AppSettings["ServiceName"] == null ? "AWL Services" : ConfigurationManager.AppSettings["ServiceName"].ToString());
			}
		}

		private string DisplayName
		{
			get
			{
                             //return GetConfigValue("displayName"); 
                             return (System.Configuration.ConfigurationManager.AppSettings["DisplayName"] == null ? "AWL Services" : ConfigurationManager.AppSettings["DisplayName"].ToString());
			}
		}
```
Then rebuild the solution and follow the installation procedure:
i) Go to Build folder and copy the files to a logical folder ( Like Program Files )
ii) CMD to this folder and run:
```C:\Windows\Microsoft.NET\Framework64\v4.0.30319\InstallUtil.exe AWL.Services.Console.exe```

-------------------------------------------

Regarding the other question the file where you need to put the storefront and DB address is appsettings.Production.json at AWL.Services.Console.

**Comment by bkvinoth** [comment]
Thanks for the valuable information, But just for clarification DisplayName is icon name(Published Application or Desktop) in the storefront, so I don't know the what is ServiceName

**Comment by manuelmarucco** [comment]
I think your are misunderstanding  what `displayName` and `serviceName` are. Both variables are depicting the windows service name, that is,  when `AWL Service Console.exe` is installed. `DisplayName` has nothing to do with icon name in storefront. 

I installed the service locally and changed both values to show you which this variable are. Please take a look at the image below:

![image](https://user-images.githubusercontent.com/9523072/34106591-887aa01c-e3d7-11e7-99c3-056889bd2488.png)

Also, you should have been able to install the service by now.

**Comment by bkvinoth** [comment]
Thanks got it
